name: ExcellentPetUtilities
version: '1.0.0'
main: com.yashhpenchi.excellentpetutilities.ExcellentPetUtilities
api-version: '26.1.2'
author: Yashh-Penchi
description: Vanilla pets, turned into utility companions.

permissions:
  expet.help:
    default: true
  expet.info:
    default: true
  expet.give:
    default: op
  expet.reload:
    default: op
  expet.debug:
    default: op
